### ISSUE TITLE
Getting this errors from doing a "make" on a clean Github copy

### ISSUE THREAD

**Issue by trsbox** [arxanas/drafts.ninja#47]
/src/config:1:1: Unexpected token .
/src/config:1:3: Unexpected token /
/src/config:1:5: Unexpected token .

**Comment by dev-id** [comment]
File `/public/src/config.js` https://github.com/arxanas/drafts.ninja/blob/master/public/src/config.js is a Symbolic Link. This may not work in a Windows environment. You will need to copy `config.client.js` from `/` to `/public/src/` and rename it to `config.js`

Also run `make install` to generate the config files from template if necessary.

**Comment by trsbox** [comment]
Ok, got past that issue.   New one now.  I am not running in windows.  Linux.  All packages up to date.

node src/make cards
/home/scorch/dr4ft/src/make/cards.js:202
  var setRaw = raw[setCode].cards;
                            ^

TypeError: Cannot read property 'cards' of undefined
    at removeBonusCards (/home/scorch/dr4ft/src/make/cards.js:202:29)
    at after (/home/scorch/dr4ft/src/make/cards.js:198:3)
    at Object.<anonymous> (/home/scorch/dr4ft/src/make/cards.js:23:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (/home/scorch/dr4ft/node_modules/traceur/src/node/require.js:65:21)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
Makefile:29: recipe for target 'cards' failed
make: *** [cards] Error 1

**Comment by tooomm** [comment]
The project in this repo is now unmaintained for a longer time.
You might want to check out the follow up repo by @dev-id with several changes already!
https://github.com/dr4fters/dr4ft

If you still run into issues open a new ticket there, please.

You most likely won't see help on this outdated code and can close this issue.

---

Did you run http://trsbox.net/ before with a mirror/fork of the old draft site @trsbox?
I remember that one. ;)
